### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [jlegar/colmar-academy#6]
Fantastic job on this project! I liked how you chose to add your own elements to the code, such as the imported font-face, as well as the comments throughout your HTML.

In terms of improvement, I recommend adding a padding and height for the info-box class in Start Learning, to streamline the white boxes. I also suggested playing around with the info-box in the first section, as it seems like the overflow isn't being properly maintained by the grid. 

If you're looking for a challenge, I'd recommend trying to switch this page to implement bootstrap. Here's a link to get you started: https://www.w3schools.com/bootstrap/. Keep up the stellar work! :D

**Comment by jlegar** [comment]
Thanks a lot for your comments and suggestions.
